### ISSUE TITLE
Discover Error in Zabbix

### ISSUE THREAD

**Issue by KavyaKanya** [aklyuk/zabbix-hp-3par#3]
Hello 

I've tried t import the Template to Zabbix and placed the scripts in the externalscripts folder of Zabbix proxy as per the mentioned instructions

I did try to run th python script and an output 1000 :/

![image](https://user-images.githubusercontent.com/69708851/97938070-720a8200-1da6-11eb-8c08-10b4c49ef02f.png)

In Zabbix when I check under the Discover below is the error it shows thought the module is installed

![image](https://user-images.githubusercontent.com/69708851/97778389-d528c880-1b9c-11eb-80ca-37e0fb9b3423.png)

![image](https://user-images.githubusercontent.com/69708851/97938049-615a0c00-1da6-11eb-8e28-343914aeb677.png)

**Comment by aklyuk** [comment]
Hi.
You need to install pywbem python module.
Example for python3:  `pip3 install pywbem`

**Comment by KavyaKanya** [comment]
> Hi.
> You need to install pywbem python module.
> Example for python3: `pip3 install pywbem`

![image](https://user-images.githubusercontent.com/69708851/97837147-aa0cb900-1d03-11eb-941d-8017ffa43c71.png)

Hello

I've installed it already post d error did try re-installing too as per the screenshot the Python library is already is what d message it displays

**Comment by aklyuk** [comment]
pip3 for python3.
In script, first line -  #!/usr/bin/python3

**Comment by KavyaKanya** [comment]
> pip3 for python3.
> In script, first line - #!/usr/bin/python3

Thank you! for the prompt response

ok! I'd install python3 related respective modules and keep you posted

**Comment by KavyaKanya** [comment]
> pip3 for python3.
> In script, first line - #!/usr/bin/python3

is it mandatory to have Python3 and related modules to be installed?

**Comment by aklyuk** [comment]
you can use python2. but you will be need change some code. 
pywbem is required for python2.

**Comment by KavyaKanya** [comment]
> you can use python2. but you will be need change some code.
> pywbem is required for python2.

So as suggested I've installed Python3 and related libraries also

But I get this errror in Zabbix

![image](https://user-images.githubusercontent.com/69708851/97957390-10134200-1dd1-11eb-8fe3-a1b97cfb33f9.png)

Other question I've this current situation 

3PAR  Management Console is installed on IP1 i.e they login to this IP1 via RDP and then open the Management console and then login to the respective 3PAR Storage with its respective IP (IP2)

So as per your 'ReadMe' in the below what IP has to be mentioned

In agent configuration file, /etc/zabbix/zabbix_agentd.conf must be set parameter ServerActive=xxx.xxx.xxx.xxx

and moreoever below is the error when I run the command

python3 ./hp_3par_get_state_wbem.py --hp_ip=**** --hp_port=8 --hp_user=**** --hp_password=**** --storage_name=**** --discovery

![image](https://user-images.githubusercontent.com/69708851/97971675-69876b00-1de9-11eb-911a-f5214259c219.png)

**Comment by BozhebayevM** [comment]
Hi, Thank You for this solution For Zabbix. I have the same problem. When i am run script manually from console of zabbix server it is works and return 0 code. But when it start by web UI i have errors like in the last Screen KavyaKanya

![image](https://user-images.githubusercontent.com/74897699/99939045-61d93780-2d93-11eb-9133-9311b5e3c08a.png)

**Comment by BozhebayevM** [comment]
> Hi, Thank You for this solution For Zabbix. I have the same problem. When i am run script manually from console of zabbix server it is works and return 0 code. But when it start by web UI i have errors like in the last Screen KavyaKanya
> 
> ![image](https://user-images.githubusercontent.com/74897699/99939045-61d93780-2d93-11eb-9133-9311b5e3c08a.png)

So i am try to add two macros $HOST.NAME and $HOST.IP and change key of trapper item and it is works. But i must run command zabbix_server -R  config_cache_reload

**Comment by BozhebayevM** [comment]
> > you can use python2. but you will be need change some code.
> > pywbem is required for python2.
> 
> So as suggested I've installed Python3 and related libraries also
> 
> But I get this errror in Zabbix
> 
> ![image](https://user-images.githubusercontent.com/69708851/97957390-10134200-1dd1-11eb-8fe3-a1b97cfb33f9.png)
> 
> Other question I've this current situation
> 
> 3PAR Management Console is installed on IP1 i.e they login to this IP1 via RDP and then open the Management console and then login to the respective 3PAR Storage with its respective IP (IP2)
> 
> So as per your 'ReadMe' in the below what IP has to be mentioned
> 
> In agent configuration file, /etc/zabbix/zabbix_agentd.conf must be set parameter ServerActive=xxx.xxx.xxx.xxx
> 
> and moreoever below is the error when I run the command
> 
> python3 ./hp_3par_get_state_wbem.py --hp_ip=**** --hp_port=8 --hp_user=**** --hp_password=**** --storage_name=**** --discovery
> 
> ![image](https://user-images.githubusercontent.com/69708851/97971675-69876b00-1de9-11eb-911a-f5214259c219.png)

My last commits it is also can helps for you

**Comment by pay748** [comment]
Thank you very much for the solution shared by aklyuk, it solved one of my problems, thank you again.Do not use root user to install python library on zabbix-server or proxy server.This operation will cause zabbix to be unable to call the corresponding library. Non-privileged users are recommended to install the python library like this: “python3 -m pip install paramiko paramiko”can help you solve some unnecessary troubles (when the script returns a code of 1000, you can find the return code of 1000In the function, add “print(oops)”before the sys.exit("1000") code in the function. This can help you locate the problem and view the detailed error message.

**Comment by joedong1988** [comment]
Ops~~
I hava a same problem.
error code as below:

    Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
    File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
    File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
    ConnectionRefusedError: [Errno 111] Connection refused
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
    File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
    File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5542c307f0>: Failed to establish a new connection: [Errno 111] Connection refused
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
    File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
    File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
    File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=5989): Max retries exceeded with url: /cimom (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5542c307f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_http.py", line 317, in wbem_request
    timeout=(HTTP_CONNECT_TIMEOUT, conn.timeout))
    File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
    File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=5989): Max retries exceeded with url: /cimom (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5542c307f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "/usr/lib/zabbix/externalscripts/hp_3par_get_state_wbem.py", line 230, in get_status_resources
    state_of_concrete_instances = hp_connect.EnumerateInstances(CIM_class, PropertyList=["OperationalStatus","HealthState", "DeviceID", "ElementName", "Tag", "SerialNumber", "SystemLED", "OtherOperationalStatus"])
    File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 2783, in EnumerateInstances
    PropertyList=PropertyList)
    File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 1824, in _imethodcall
    self, request_data, cimxml_headers)
    File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_http.py", line 323, in wbem_request
    raise ConnectionError(msg, conn_id=conn.conn_id)
    pywbem._exceptions.ConnectionError: Failed to establish a new connection: [Errno 111] Connection refused; OpenSSL version used: OpenSSL 1.0.2k-fips 26 Jan 2017
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "/usr/lib/zabbix/externalscripts/hp_3par_get_state_wbem.py", line 379, in <module>
    main()
    File "/usr/lib/zabbix/externalscripts/hp_3par_get_state_wbem.py", line 363, in main
    arguments.zbx_ip, arguments.zbx_port)
    File "/usr/lib/zabbix/externalscripts/hp_3par_get_state_wbem.py", line 268, in get_status_resources
    except pywbem.exceptions.TimeoutError as oops:
    AttributeError: module 'pywbem' has no attribute 'exceptions'"

**Comment by joedong1988** [comment]
I test the scripts on zabbix web interface,show me :Timeout while executing a shell script.
please help me.

**Comment by joedong1988** [comment]
I have fixed the issue.

**Comment by blablas** [comment]
hi @joedong1988, how did you fix it?
Please, help me...I'm stuck

**Comment by blablas** [comment]
Ok, resolved. For everyone who may need, you must increase the "Timeout" value in zabbix-server.conf (default= 4) to something higher and restart the zabbix-server service
